### ISSUE TITLE
ID Conflict or weird crash?

### ISSUE THREAD

**Issue by Sunconure11** [whichonespink44/Appalachia#15]
Trying to slowly make a port of my pack to 1.10.2, and I decided to try this mod out. However, I quickly found this crash upon loading.

http://pastebin.com/aSdwZepG

I haven't ironed out ID conflicts yet should they exist, but this does not seem like an ID conflict.

**Comment by whichonespink44** [comment]
Ah, I think this is because the current alpha release of Appalachia requires RTG version 4.1.1.3 and only version 4.1.1.3.

In the future we'll make sure the min/max version requirements are correct. In the meantime, if you want to test out Appalachia, you'll need to either use RTG version 4.1.1.3 or wait until we release the next version, which should hopefully be in the next week or two.

**Comment by srs-bsns** [comment]
It could be an ID conflict.

Appalachia will load before most mods (alphabetical ordering) so it will grab the first available IDs (lower 40's) which might already be set in another mod like BoP. So you may have to make some ID adjustments.

As for adding Appalachia to a modpack, you need to understand that what you are using is the first Alpha release. It's not meant to be used seriously at this time, and the mod is about to be under heavy development. You should probably wait until we have a more stable release.

**Comment by srs-bsns** [comment]
FFS, quit being a ninja already! :(

**Comment by Sunconure11** [comment]
Pack is far from release, I'm just adding it now since I have been eyeing this mod for a bit.
